function bw-sync --description "Generate SSH config from Bitwarden SSH agent identities"

    if test (count $argv) -eq 0
        echo "Usage:"
        echo "  bw-sync all"
        echo "  bw-sync include <identity>..."
        echo "  bw-sync exclude <identity>..."
        return 1
    end

    set -l mode $argv[1]

    switch $mode
        case all include exclude
        case '*'
            echo "Invalid mode: $mode"
            echo "Use: all | include | exclude"
            return 1
    end


    # Normalize filters
    set -l filters

    for item in $argv[2..-1]
        set -a filters (
            echo $item \
            | string lower \
            | string replace -ra '[^a-z0-9._-]+' '-' \
            | string trim -c '-'
        )
    end


    set -l sshdir ~/.ssh/bw
    set -l sshconfigdir ~/.ssh/config.d
    set -l cfg $sshconfigdir/bitwarden.conf
    set -l maincfg ~/.ssh/config

    mkdir -p $sshdir
    mkdir -p $sshconfigdir


    # Ensure OpenSSH loads config.d
    if not test -f $maincfg
        touch $maincfg
    end

    if not grep -qxF "Include ~/.ssh/config.d/*" $maincfg
        printf "\nInclude ~/.ssh/config.d/*\n" >> $maincfg
    end


    printf "# Generated by bw-sync\n\n" > $cfg


    for line in (ssh-add -L)

        if string match -qr '^The agent has no identities' -- $line
            continue
        end


        set -l parts (string split ' ' $line)

        if test (count $parts) -lt 3
            continue
        end


        # Keep full SSH comment
        set -l comment (string join " " $parts[3..-1])


        # Normalize name
        set -l name (
            echo $comment \
            | string lower \
            | string replace -ra '[^a-z0-9._-]+' '-' \
            | string trim -c '-'
        )


        if test -z "$name"
            continue
        end


        switch $mode
            case include
                if not contains -- $name $filters
                    continue
                end

            case exclude
                if contains -- $name $filters
                    continue
                end
        end


        # Save public key only
        printf "%s\n" $line > "$sshdir/$name.pub"


        # Generate identity config only
        printf "Host %s\n" $name >> $cfg
        printf "    IdentityFile %s/%s.pub\n" $sshdir $name >> $cfg
        printf "    IdentitiesOnly yes\n\n" >> $cfg

    end


    echo "Generated:"
    echo "$cfg"

end
