function bw-ssh-sync --description "Generate SSH config from Bitwarden SSH agent"

    set -l bwdir ~/.ssh/bw
    set -l cfgdir ~/.ssh/config.d
    set -l cfg $cfgdir/bitwarden.conf
    set -l manifest $bwdir/manifest.fish
    set -l sshconfig ~/.ssh/config

    mkdir -p $bwdir
    mkdir -p $cfgdir

    if not test -f $manifest
        echo "Missing manifest: $manifest"
        return 1
    end

    source $manifest

    # Ensure ssh loads config.d
    if not test -f $sshconfig
        touch $sshconfig
    end

    if not grep -qxF "Include ~/.ssh/config.d/*" $sshconfig
        printf "\nInclude ~/.ssh/config.d/*\n" >> $sshconfig
    end

    printf "# Generated by bw-ssh-sync\n\n" > $cfg


    # Export public keys only
    for line in (ssh-add -L)

        if string match -qr '^The agent has no identities' -- $line
            continue
        end

        set -l parts (string split " " $line)

        if test (count $parts) -lt 3
            continue
        end

        set -l comment (string join " " $parts[3..-1])

        set -l name (
            echo $comment \
            | string lower \
            | string replace -ra '[^a-z0-9._-]+' '-' \
            | string trim -c '-'
        )

        if test -z "$name"
            continue
        end

        printf "%s\n" $line > $bwdir/$name.pub

    end


    # Generate complete SSH config
    for entry in $BW_HOSTS

        set -l parts (string split "|" $entry)

        set -l name $parts[1]
        set -l user $parts[2]
        set -l host $parts[3]


        printf "Host %s\n" $name >> $cfg

        if test -n "$user"
            printf "    User %s\n" $user >> $cfg
        end

        printf "    HostName %s\n" $host >> $cfg
        printf "    IdentityFile %s/%s.pub\n" $bwdir $name >> $cfg
        printf "    IdentitiesOnly yes\n" >> $cfg
        printf "    SetEnv TERM=xterm-256color\n\n" >> $cfg

    end


    echo "Generated:"
    echo "$cfg"

end
