# ~/.config/aerospace/aerospace.toml
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Core Settings                                       ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = [
  'move-mouse window-lazy-center'
  # 'exec-and-forget sketchybar --trigger aerospace_focus_change',
]

automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'


# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Gaps                                                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 7
outer.right = 7
outer.top = 6
outer.bottom = 6


# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Main Binding Mode                                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
[mode.main.binding]

# ─────────────────────────────────────────────────────
# Launchers
# ─────────────────────────────────────────────────────

alt-enter = 'exec-and-forget osascript -e "tell application \"iTerm\" to create window with default profile"'
alt-e = "exec-and-forget osascript -e 'tell application \"Finder\" to make new Finder window to (path to home folder)'"
alt-b = "exec-and-forget osascript -e 'tell application \"Helium\" to make new window'"
ctrl-alt-b = "exec-and-forget osascript -e 'tell application \"Helium\" to make new window with properties {mode:\"incognito\"}'"
alt-space = 'exec-and-forget open -a Raycast'

# ─────────────────────────────────────────────────────
# Window
# ─────────────────────────────────────────────────────

ctrl-alt-enter = 'fullscreen'
ctrl-alt-c = ['layout floating', 'resize smart -300', 'move-mouse window-force-center']
ctrl-alt-minus = 'resize smart -50'
ctrl-alt-equal = 'resize smart +50'

ctrl-alt-tab = 'workspace-back-and-forth'
alt-q = 'close'


# ─────────────────────────────────────────────────────
# Focus
# ─────────────────────────────────────────────────────

ctrl-alt-left = 'focus left'
ctrl-alt-right = 'focus right'
ctrl-alt-up = 'focus up'
ctrl-alt-down = 'focus down'


# ─────────────────────────────────────────────────────
# Move
# ─────────────────────────────────────────────────────

alt-shift-left  = 'move left'
alt-shift-right = 'move right'
alt-shift-up    = 'move up'
alt-shift-down  = 'move down'


# ─────────────────────────────────────────────────────
# Workspaces
# ─────────────────────────────────────────────────────

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-period = 'workspace next'
alt-comma  = 'workspace prev'

alt-shift-period = 'move-workspace-to-monitor --wrap-around next'
alt-shift-comma  = 'move-workspace-to-monitor --wrap-around prev'


# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Service Binding Mode                                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    f = ['flatten-workspace-tree', 'mode main']
    r = ['layout floating tiling', 'mode main']
    j = ['layout tiles horizontal vertical', 'mode main']
    k = ['layout accordion horizontal vertical', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-up = ['join-with up', 'mode main']
    alt-shift-down = ['join-with down', 'mode main']
    alt-shift-left = ['join-with left', 'mode main']
    alt-shift-right = ['join-with right', 'mode main']


# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Window Configuration                                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Chrome PiP
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'Picture-in-picture'
run = 'layout floating'
check-further-callbacks = true

# Helium PiP
[[on-window-detected]]
if.app-id = 'net.imput.helium'
if.window-title-regex-substring = "Picture in Picture"
run = "layout floating"
check-further-callbacks = true

# Utilities
[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.jordanbaird.Ice'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.wireguard.MacOS'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.obsproject.obs-studio'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.alienator88.Pearcleaner'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.neohtop.dev'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.titanium.Onyx'
run = ['layout floating']
