# ~/.aerospace.toml

after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = [
  # 'move-mouse window-lazy-center',
  'exec-and-forget sketchybar --trigger aerospace_focus_change',
]

automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
inner.horizontal = 3
inner.vertical = 3
outer.left = 5
outer.top = 5
outer.bottom = 5
outer.right = 5

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Main Binding Mode                                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
[mode.main.binding]

# ── Launchers ─────────────────────────────────────────
alt-enter = 'exec-and-forget open -n -a iTerm' # iTerm
alt-e = 'exec-and-forget open ~'        # File manager
alt-space = 'exec-and-forget open -a Raycast' # App launcher

# ── Window Actions ────────────────────────────────────
alt-q = 'close'
#alt-shift-m = 'exec-and-forget loginctl terminate-user ""'
alt-v = 'layout floating tiling' # toggle floating/tiling
alt-f = 'fullscreen'
alt-j = 'layout tiles horizontal vertical'
alt-k = 'layout accordion horizontal vertical'
alt-tab = 'workspace-back-and-forth'
alt-period = 'workspace next'
alt-comma  = 'workspace prev'

# ── Focus Movement ────────────────────────────────────
alt-left  = 'focus left'
alt-right = 'focus right'
alt-up    = 'focus up'
alt-down  = 'focus down'

# ── Window Movement ───────────────────────────────────
alt-shift-left  = 'move left'
alt-shift-right = 'move right'
alt-shift-up    = 'move up'
alt-shift-down  = 'move down'

# ── Resize ────────────────────────────────────────────
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# ── Workspaces ────────────────────────────────────────
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# ── Workspaces Move ───────────────────────────────────────
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-period = 'move-workspace-to-monitor --wrap-around next'
alt-shift-comma = 'move-workspace-to-monitor --wrap-around prev'

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Service Binding Mode                                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']


# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Window Configuration                                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
if.window-title-regex-substring = 'Picture-in-Picture'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'Picture-in-picture'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.jordanbaird.Ice'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.wireguard.MacOS'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.alienator88.Pearcleaner'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.neohtop.dev'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.titanium.Onyx'
run = ['layout floating']
